[package]
name = "lines-king"
version = "0.1.0"
authors = ["Jens Fredskov <jensfredskov@protonmail.ch>"]

[[bin]]
name = "lines-king"

[dependencies]
piston = "0.27.0"
piston2d-graphics = "0.19.0"
pistoncore-glutin_window = "0.33.0"
piston2d-opengl_graphics = "0.37.0"
nalgebra = "0.10.1"
